version: 2
updates:
    # Main extension dependencies
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
      ignore:
          # Ignore all non-security updates (security vulnerabilities bypass these ignore rules)
          - dependency-name: "*"
            update-types:
                - "version-update:semver-major"
                - "version-update:semver-minor"
                - "version-update:semver-patch"

    # Webview UI dependencies
    - package-ecosystem: "npm"
      directory: "/webview-ui"
      schedule:
          interval: "weekly"
      ignore:
          # Ignore CRA and related packages that often have false positives
          - dependency-name: "react-scripts"
          - dependency-name: "@testing-library/*"
          - dependency-name: "web-vitals"
          - dependency-name: "*"
            update-types:
                - "version-update:semver-major"
                - "version-update:semver-minor"
                - "version-update:semver-patch"
