name: "Changie Version PR"

on:
    push:
        branches:
            - main

jobs:
    version-pr:
        name: Create/Update Version PR
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Important for changelog history

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.15.1

            - name: Install dependencies
              run: npm ci

            # Use Changie to batch changes and get the next version
            - name: Batch changes
              id: batch
              uses: miniscruff/changie-action@v2
              with:
                  args: batch auto

            # If no changes, stop here
            - name: Check for changes
              id: check
              run: |
                  if [ -z "$(git status --porcelain)" ]; then
                    echo "No changes to process"
                    echo "has_changes=false" >> $GITHUB_OUTPUT
                  else
                    echo "has_changes=true" >> $GITHUB_OUTPUT
                  fi

            # If we have changes, merge them and create/update PR
            - name: Merge changes
              if: steps.check.outputs.has_changes == 'true'
              uses: miniscruff/changie-action@v2
              with:
                  args: merge

            - name: Get latest version
              if: steps.check.outputs.has_changes == 'true'
              id: latest
              uses: miniscruff/changie-action@v2
              with:
                  args: latest

            - name: Create Pull Request
              if: steps.check.outputs.has_changes == 'true'
              uses: peter-evans/create-pull-request@v4
              with:
                  title: "Release ${{ steps.latest.outputs.output }}"
                  branch: "release/${{ steps.latest.outputs.output }}"
                  commit-message: "chore: update changelog for ${{ steps.latest.outputs.output }}"
                  body: |
                      This PR was automatically created by the Changie workflow.
                      - Updates CHANGELOG.md
                      - Bumps version to ${{ steps.latest.outputs.output }}
