name: Check Changeset
run-name: Check for Changeset in PR

on:
    pull_request:
        branches:
            - main
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    check-changeset:
        # Skip draft PRs and dependabot PRs
        if: github.event.pull_request.draft == false && github.actor != 'dependabot[bot]'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Check for changeset
              id: check-changeset
              run: |
                  # Get list of changed files
                  CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
                  echo "Changed files:"
                  echo "$CHANGED_FILES"

                  # Check if any of the changed files are in docs/ or .github/
                  DOCS_ONLY=true
                  while IFS= read -r file; do
                    if [[ ! "$file" =~ ^(docs/|.github/) ]]; then
                      DOCS_ONLY=false
                      break
                    fi
                  done <<< "$CHANGED_FILES"

                  # If changes are docs-only, skip changeset check
                  if [ "$DOCS_ONLY" = true ]; then
                    echo "Only documentation files were changed, skipping changeset check"
                    exit 0
                  fi

                  # Count number of changeset files (excluding README.md)
                  CHANGESETS=$(find .changeset -name "*.md" ! -name "README.md" | wc -l | tr -d ' ')
                  echo "Number of changesets: $CHANGESETS"

                  if [ "$CHANGESETS" -eq 0 ]; then
                    echo "::error::No changeset file found. Please run 'npm run changeset' to create one."
                    exit 1
                  fi

            - name: Find Comment
              uses: peter-evans/find-comment@v3
              if: failure()
              id: find-comment
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  comment-author: "github-actions[bot]"
                  body-includes: This PR requires a changeset

            - name: Create Comment
              uses: peter-evans/create-or-update-comment@v4
              if: failure() && steps.find-comment.outputs.comment-id == ''
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      This PR requires a changeset since it includes user-facing changes. Please:

                      1. Run `npm run changeset` locally
                      2. Choose the appropriate version bump:
                         - `major` for breaking changes (1.0.0 → 2.0.0)
                         - `minor` for new features (1.0.0 → 1.1.0)
                         - `patch` for bug fixes (1.0.0 → 1.0.1)
                      3. Write a clear description of your changes
                      4. Commit the generated changeset file

                      Note: Documentation-only changes do not require a changeset.
